# Generated by Django 5.2.3 on 2025-06-24 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuelos', '0002_pasajero_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5)),
                ('clase', models.CharField(choices=[('economica', 'Economica'), ('ejecutiva', 'Ejecutiva')], max_length=20)),
                ('reservado', models.BooleanField(default=False)),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos.vuelo')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_checkin', models.DateTimeField(auto_now_add=True)),
                ('asiento', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vuelos.asiento')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vuelos.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Equipaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo', models.CharField(choices=[('cabina', 'Cabina'), ('documento', 'Documento')], max_length=20)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelos.checkin')),
            ],
        ),
    ]
